# NumPy Introduction

## What is NumPy?

NumPy stands for Numerical Python.

It is an open-source Python library used for numerical computing.

NumPy provides:
- Fast array operations
- Multi-dimensional arrays
- Mathematical functions
- Linear algebra
- Statistical operations
- Random number generation

NumPy is the foundation of many Data Science and Machine Learning libraries such as Pandas, Scikit-learn, TensorFlow, and PyTorch.m

## Why Do We Need NumPy?

Python lists are flexible and easy to use, but they become slow and memory-inefficient when working with large amounts of numerical data.

NumPy solves this problem by storing data more efficiently and performing calculations much faster.

For this reason, NumPy is one of the most important libraries in Data Science.

## Python List vs NumPy Array

Python List
- Can store different data types
- Slower for numerical calculations
- Uses more memory

NumPy Array
- Stores elements of the same data type
- Faster numerical operations
- Uses less memory

In [3]:
import numpy as np

In [6]:
arr = np.array([10, 20, 30, 40, 50])

arr

array([10, 20, 30, 40, 50])

In [7]:
type(arr)

numpy.ndarray

In [8]:
my_list = [10, 20, 30, 40, 50]

type(my_list)

list

## What does `import numpy as np` mean?

- `import` → Loads the NumPy library.
- `numpy` → The library name.
- `as np` → Creates a short alias.

Instead of writing:

numpy.array([1, 2, 3])

we simply write:

np.array([1, 2, 3])

This is the standard convention followed by Python developers and data scientists.

In [10]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print(a)
print(b)
print(c)
type(a)

[1 2 3]
[4 5 6]
[7 8 9]


numpy.ndarray

In [11]:
import numpy as np
marks=np.array([85,92,78,88,95])
print(marks)
print(type(marks))

[85 92 78 88 95]
<class 'numpy.ndarray'>


## Key Takeaways

- NumPy stands for Numerical Python.
- NumPy is used for numerical computations.
- NumPy arrays are faster than Python lists for numerical operations.
- NumPy arrays store elements of the same data type.
- We import NumPy using `import numpy as np`.
- The main object in NumPy is `numpy.ndarray`.

## Dimensions in NumPy

1D Array → A single row of numbers.

2D Array → Rows and columns (like a table).

3D Array → A stack of tables.

In [18]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(a.ndim)

[1 2 3 4 5]
1


In [19]:
b=np.array([[1,2,3],
    [4,5,6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [20]:
c = np.array([[[1, 2], [3, 4]],

              [[5, 6], [7, 8]]])

print(c)
print(c.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [22]:
x = np.array([10, 20, 30])

y = np.array([[1, 2],
              [3, 4]])

z = np.array([[[1], [2]],
              [[3], [4]]])

print(x.ndim)
print(y.ndim)
print(z.ndim)

1
2
3
