# NumPy - Array Creation
## Creating Arrays in NumPy

## 1. np.array()

The `np.array()` function is used to convert Python sequences such as lists or tuples into NumPy arrays.

Syntax:

np.array(object)

In [2]:
import numpy as np
numbers=[10,20,30,40,50]
arr=np.array(numbers)
print(arr)

[10 20 30 40 50]


In [3]:
type(arr)

numpy.ndarray

In [4]:
numbers = (1,2,3,4)
arr = np.array(numbers)
print(arr)

[1 2 3 4]


In [5]:
import numpy as np
a=np.array([1,2,3])
b=np.array((4,5,6))
c=np.array([[7,8],[9,10]])
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))

[1 2 3]
[4 5 6]
[[ 7  8]
 [ 9 10]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


## Key Takeaways

- `np.array()` converts Python sequences into NumPy arrays.
- It can convert lists, tuples, and nested lists.
- The output object type is `numpy.ndarray`.
- NumPy displays arrays differently from Python lists.

## 2. np.zeros()

`np.zeros()` creates an array filled with zeros.

Syntax:

np.zeros(shape)

In [7]:
import numpy as np
arr=np.zeros(5)
print(arr)
arr.dtype

[0. 0. 0. 0. 0.]


dtype('float64')

In [10]:
arr=np.zeros(5,dtype=int)
print(arr)

[0 0 0 0 0]


In [11]:
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [15]:
b=np.zeros((3,2))
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
c=np.zeros((2,2),dtype=int)
print(c)

[[0 0]
 [0 0]]


## 3. np.ones()

The `np.ones()` function creates a new NumPy array filled with ones.

Syntax:

np.ones(shape)

In [18]:
import numpy as np
arr = np.ones(5)
print(arr)
arr.dtype

[1. 1. 1. 1. 1.]


dtype('float64')

In [19]:
arr = np.ones(5,dtype=int)
print(arr)
arr.dtype

[1 1 1 1 1]


dtype('int64')

In [20]:
arr=np.ones((3,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
arr=np.ones((2,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## 4. np.empty()

The `np.empty()` function creates an array without initializing its values.

It allocates memory for the array but does not fill it with any specific values.

In [22]:
import numpy as np
arr=np.empty(5)
print(arr)

[5.e-324 5.e-324 5.e-324 5.e-324 5.e-324]


In [23]:
arr = np.empty((2,3))

print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
a = np.empty(4)
print(a)

[3.5e-323 4.0e-323 4.4e-323 4.9e-323]


In [25]:
b = np.empty((2,2))
print(b)

[[3.5e-323 4.0e-323]
 [4.4e-323 4.9e-323]]


In [28]:
c = np.empty(3)
c[:] = [100, 200, 300]
print(c)

[100. 200. 300.]


In [29]:
arr = np.array([10,20,30,40,50])
arr[:] = 99
print(arr)

[99 99 99 99 99]


In [30]:
arr = np.array([10,20,30,40,50])
arr[1:4] = [100,200,300]
print(arr)

[ 10 100 200 300  50]


## 5. np.arange()

`np.arange()` creates a NumPy array containing evenly spaced values within a given range.

Syntax:

np.arange(start, stop, step)

In [1]:
import numpy as np
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [2]:
b=np.arange(2,8)
print(b)

[2 3 4 5 6 7]


In [3]:
arr=np.arange(2,11,2)
print(arr)

[ 2  4  6  8 10]


In [4]:
arr=np.arange(10,0,-2)
print(arr)

[10  8  6  4  2]


## 6. np.linspace()

The `np.linspace()` function creates evenly spaced numbers between a start and stop value.

Unlike `np.arange()`, you specify the **number of values**, not the step size.

Syntax:

np.linspace(start, stop, num)

In [10]:
import numpy as np
arr=np.linspace(1,5,5)
print(arr)

[1. 2. 3. 4. 5.]


In [11]:
arr=np.linspace(0,10,6)
print(arr)

[ 0.  2.  4.  6.  8. 10.]


In [12]:
arr=np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [13]:
a = np.linspace(1,5,5)
print(a)
b = np.linspace(0,20,5)
print(b)
c = np.linspace(100,200,6)
print(c)

[1. 2. 3. 4. 5.]
[ 0.  5. 10. 15. 20.]
[100. 120. 140. 160. 180. 200.]


In [14]:
arr=np.linspace(0,1,50)
print(arr)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


## 7. np.eye()

The `np.eye()` function creates an identity matrix.

An identity matrix is a square matrix in which:
- All diagonal elements are 1.
- All other elements are 0.

Syntax:

np.eye(N)

np.eye(N,M) can also create non-square matrices.

In [15]:
import numpy as np
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
arr=np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## 8. np.identity()

The `np.identity()` function also creates an identity matrix.

Syntax:

np.identity(n)

It only create a square identity matrix

In [18]:
arr=np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 9. np.full()

The `np.full()` function creates an array filled with a specified value.

Syntax:

np.full(shape, fill_value)

In [19]:
arr=np.full(5,7)
print(arr)

[7 7 7 7 7]


In [20]:
arr=np.full((2,3),100)
print(arr)

[[100 100 100]
 [100 100 100]]


In [21]:
arr=np.full((3,3),5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
