# Notebook 03 : Array Attributes

In this notebook, we will learn how to inspect NumPy arrays.

Topics Covered:

- ndim
- shape
- size
- dtype
- itemsize
- nbytes
- astype()

## 1. ndim

`ndim` stands for **Number of Dimensions**.

It tells us how many dimensions (axes) a NumPy array has.

In [1]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
print(arr.ndim)

[10 20 30 40]
1


In [2]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr)
print(arr.ndim)

[[10 20 30]
 [40 50 60]]
2


In [4]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])
print(arr)
print(arr.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [6]:
a = np.array([1,2,3])
print(a.ndim)

1


In [7]:
b = np.array([[1,2],[3,4]])
print(b.ndim)

2


In [8]:
c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(c.ndim)

3


## 2. shape

The `shape` attribute returns the size of each dimension of a NumPy array.

It tells us how many rows and columns an array has.

In [9]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr.shape)

(2, 3)


In [10]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr.shape)

(4,)


A 1D array's shape is (4,), not (4).

The comma tells Python this is a tuple.

In [11]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr.shape)

(2, 3)


In [12]:
arr = np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(arr.shape)

(3, 2)


In [13]:
arr = np.array([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]
])

print(arr.shape)

(2, 2, 2)


In [17]:
a=np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [19]:
b=np.array([
    [1,2,3],
    [4,5,6]
    ])
print(b.shape)
print(b.ndim)

(2, 3)
2


In [20]:
c = np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(c.shape)

(3, 2)


## 3. size

The `size` attribute returns the **total number of elements** present in a NumPy array.

Syntax:

array.size

In [21]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])
print(arr.size)

6


In [22]:
import numpy as np
arr=np.array([10,20,30,40])
print(arr.size)

4


In [23]:
arr = np.array([
    [10,20,30],
    [40,50,60]
])

print(arr.size)

6


In [24]:
arr = np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(arr.size)

6


## 4. dtype

The `dtype` attribute tells us the data type of the elements stored in a NumPy array.

Syntax:

array.dtype

In [25]:
import numpy as np
arr = np.array([10,20,30])
print(arr.dtype)

int64


In [26]:
arr = np.array([1.5,2.5,3.5])
print(arr.dtype)

float64


In [27]:
arr = np.array(["Apple","Banana","Mango"])
print(arr.dtype)

<U6


In [28]:
arr = np.array([10,20.5,30])

print(arr)
print(arr.dtype)

[10.  20.5 30. ]
float64


## 5. itemsize

The `itemsize` attribute returns the size (in bytes) of **one element** in a NumPy array.

Syntax:

array.itemsize

In [30]:
import numpy as np
arr = np.array([10,20,30])
print(arr.dtype)
print(arr.itemsize)



int64
8


In [31]:
arr = np.array([1.5,2.5,3.5])

print(arr.dtype)
print(arr.itemsize)

float64
8


In [35]:
arr = np.array([1,2,3], dtype=np.int32)

print(arr.dtype)
print(arr.itemsize)

int32
4


## 6. nbytes

The `nbytes` attribute returns the **total memory occupied by the entire NumPy array** in bytes.

Syntax:

array.nbytes

nbytes = size × itemsize

In [36]:
import numpy as np
arr = np.array([10,20,30])
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

3
8
24


In [37]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

6
8
48


In [39]:
arr=np.array([1,2,3],dtype=np.int32)
print(arr.nbytes)

12


## 7. astype()

The `astype()` method is used to convert the data type of a NumPy array.

Syntax:

array.astype(new_dtype)

In [43]:
import numpy as np
arr=np.array([10,20,30])
print(arr.dtype)
new_arr=arr.astype(float)
print(new_arr)
print(new_arr.dtype)

int64
[10. 20. 30.]
float64


In [44]:
arr = np.array([1,2,3])
new_arr = arr.astype(float)
print(arr.dtype)
print(new_arr.dtype)

int64
float64


In [45]:
arr = np.array([1.2,2.8,3.9])
new_arr = arr.astype(int)
print(new_arr)

[1 2 3]


⚠️ Important:

astype(int) does not round the values.

It removes the decimal part (truncates).

Examples:

1.9 → 1
2.1 → 2
3.99 → 3

In [46]:
arr = np.array([10,20,30])
new_arr = arr.astype(str)
print(new_arr)
print(new_arr.dtype)

['10' '20' '30']
<U21
