# Array Indexing and Slicing
# 1D Indexing

**Indexing** is used to access individual elements of a NumPy array using their position (index).

**Syntax:**
```python
array[index]
```

> NumPy uses **zero-based indexing**, so the first element is at index `0`.


In [1]:
import numpy as np 
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[4])

10
30
50


In [2]:
# Using indexing in calculations

arr = np.array([5, 10, 15])
result = arr[0] + arr[2]
print(result)

20


# Negative Indexing

Negative indexing allows you to access elements from the **end** of a NumPy array.

Instead of counting from the beginning (`0, 1, 2...`), negative indexing counts from the end (`-1, -2, -3...`).

**Syntax:**
```python
array[-index]
```

> `-1` refers to the last element, `-2` to the second last, and so on.

In [3]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[-1])

50


In [4]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Last Element:", arr[-1])
print("Second Last Element:", arr[-2])
print("Third Last Element:", arr[-3])

Last Element: 50
Second Last Element: 40
Third Last Element: 30


In [5]:
names = np.array(["Rahul", "Amit", "Priya", "Riya"])
print(names[-1])
print(names[-2])

Riya
Priya


In [6]:
arr = np.array([5, 10, 15, 20])
result = arr[-1] + arr[-2]
print(result)

35


# 2D Indexing

A 2D array has **rows** and **columns**. To access an element, specify both the row and column index.

**Syntax:**
```python
array[row_index, column_index]
```

> Row and column indexing both start from `0`.

In [8]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr)
print(arr[0, 0])
print(arr[1, 2])
print(arr[2, 1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
60
80


In [10]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
row = 1
col = 0

print(arr[row, col])

40


In [13]:
students = np.array([
    ["Rahul", "Amit"],
    ["Priya", "Riya"]
])

print(students[1, 0])
print(students[0, 1])
print(students[1])

Priya
Amit
['Priya' 'Riya']


# 3D Indexing

A **3D array** is made up of multiple **2D arrays**.

To access an element, specify:

```python
array[depth, row, column]
```

Where:
- **depth** → Which 2D array (layer)
- **row** → Row inside that layer
- **column** → Column inside that row

> Indexing starts from `0` for all three dimensions.

In [15]:
import numpy as np
arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [16]:
print(arr[0, 0, 0])   # Layer 0, Row 0, Column 0
print(arr[0, 1, 2])   # Layer 0, Row 1, Column 2
print(arr[1, 0, 1])   # Layer 1, Row 0, Column 1

1
6
8


In [17]:
print(arr[1,1,2])

12


In [18]:
print(arr[-1,-1,-1])

12


In [19]:
print(arr[0])

[[1 2 3]
 [4 5 6]]


In [20]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr[1,0,1])

6


In [21]:
arr = np.array([
    [[10,20],[30,40]],
    [[50,60],[70,80]]
])

print(arr[0,1,0])

30


In [22]:
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

print(arr[0])

[[1 2]
 [3 4]]


In [23]:
arr = np.array([
    [[9,8],[7,6]],
    [[5,4],[3,2]]
])

print(arr[-1,-1,-1])

2


In [24]:
arr = np.array([
    [[1]]
])

print(arr[1,0,0]) #It will produce Error

IndexError: index 1 is out of bounds for axis 0 with size 1

# 1D Slicing

Slicing is used to extract **multiple elements** from an array.

**Syntax:**
```python
array[start:stop]
```

- `start` → Starting index (included)
- `stop` → Ending index (excluded)

> Remember: **Start is included, Stop is excluded.**


In [25]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4])

[20 30 40]


In [28]:
print(arr[:3])
print(arr[2:])
print(arr[:])

[10 20 30]
[30 40 50 60]
[10 20 30 40 50 60]


In [29]:
print(arr[3:4])

[40]


In [32]:
print(arr[3])    # scalar value

print(arr[3:4])  # NumPy array

40
[40]


In [33]:
names = np.array(["Rahul", "Amit", "Priya", "Riya", "Neha"])
print(names[1:4])

['Amit' 'Priya' 'Riya']


# 2D Slicing

2D slicing allows you to extract specific **rows**, **columns**, or **sub-arrays** from a 2D NumPy array.

**Syntax:**
```python
array[row_start:row_stop, column_start:column_stop]
```

> The part before the comma slices **rows** and the part after the comma slices **columns**.

> arr[0:2, 1:3]

>  This means:

        Rows → 0 to 1
        Columns → 1 to 2

In [34]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [35]:
print(arr[0:2])

[[10 20 30]
 [40 50 60]]


In [37]:
print(arr[:,1:3])
print(arr[0:2,1:3])

[[20 30]
 [50 60]
 [80 90]]
[[20 30]
 [50 60]]


In [39]:
print(arr[:, 0])
print(arr[1, :])

[10 40 70]
[40 50 60]


# Step Slicing

Step slicing allows you to skip elements while slicing an array.

**Syntax:**
```python
array[start:stop:step]
```

- `start` → Starting index (included)
- `stop` → Ending index (excluded)
- `step` → Number of positions to move each time

> By default, the step value is `1`.

In [40]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[0:6:2])

[10 30 50]


In [41]:
print(arr[::3])

[10 40]


In [43]:
print(arr[:5:2])
print(arr[1::2])

[10 30 50]
[20 40 60]


In [44]:
names = np.array([
    "Rahul",
    "Amit",
    "Priya",
    "Riya",
    "Neha",
    "Karan"
])

print(names[::2])

['Rahul' 'Priya' 'Neha']


In [45]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90],
    [100,110,120]
])

print(arr[::2])

[[10 20 30]
 [70 80 90]]


For 2-D slicing

array[row_start:row_stop:row_step, column_start:column_stop:column_step]

In [47]:
import numpy as np

arr = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])

print(arr)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [50]:
print(arr[1:3, :])
print(arr[:, 1:3])
print(arr[1:3, 1:3])

[[21 22 23 24]
 [31 32 33 34]]
[[12 13]
 [22 23]
 [32 33]
 [42 43]]
[[22 23]
 [32 33]]


In [55]:
print(arr[::2, :])
print(arr[:, ::2])
print(arr[::2, ::2])
print(arr[1::2, ::2])
print(arr[0:4:2, 1:4:2])

[[11 12 13 14]
 [31 32 33 34]]
[[11 13]
 [21 23]
 [31 33]
 [41 43]]
[[11 13]
 [31 33]]
[[21 23]
 [41 43]]
[[12 14]
 [32 34]]


# Reverse Slicing

Reverse slicing is used to traverse an array **from the end to the beginning**.

It is achieved by using a **negative step**.

**Syntax:**
```python
array[start:stop:-1]
```

or simply

```python
array[::-1]
```

> A negative step moves from right to left.

In [60]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[::-1])
print(arr[3:0:-1])
print(arr[::-2])

[50 40 30 20 10]
[40 30 20]
[50 30 10]


In [61]:
names = np.array(["Rahul", "Amit", "Priya", "Riya"])
print(names[::-1])

['Riya' 'Priya' 'Amit' 'Rahul']


In [66]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr[::-1,:])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [63]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr[:,::-1])

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [64]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


# Fancy Indexing

Fancy indexing allows you to select multiple specific elements, rows, or columns using lists or arrays of indices.

**Syntax (1D):**
```python
array[[index1, index2, index3]]
```

**Syntax (2D):**
```python
array[[row_indices]]
array[:, [column_indices]]
```

> Fancy indexing selects exactly the indices you specify. They do not have to be consecutive.

In [68]:
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,5]])

[10 30 60]


In [70]:
print(arr[[1,1,3]]) #Duplicate indices also work here

[20 20 40]


In [71]:
print(arr[[5,2,0]])

[60 30 10]


In [76]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90],
    [100,110,120]
])

print(arr[[0,2],:])  # For Rows
print(arr[:,[0,2]])  # For Columns

[[10 20 30]
 [70 80 90]]
[[ 10  30]
 [ 40  60]
 [ 70  90]
 [100 120]]


In [82]:
print(arr[[0,2]][:,[0,2]])

[[10 30]
 [70 90]]


# Boolean Indexing

Boolean indexing is used to filter array elements based on a condition.

**Syntax:**
```python
array[condition]
```

The condition returns a Boolean array (`True`/`False`), and NumPy selects only the elements where the value is `True`.

> Boolean indexing is commonly used for data filtering and cleaning.

In [83]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr > 25])

[30 40 50]


In [86]:
import numpy as np
arr = np.array([10,20,30,40,50])
mask = arr > 25

print(mask)
print(arr[mask])

[False False  True  True  True]
[30 40 50]


In [87]:
print(arr[arr > 25])

[30 40 50]


In [88]:
print(arr[arr%2 == 0])

[10 20 30 40 50]


In [89]:
arr = np.array([1,2,3,4,5,6])
print(arr[arr % 2 == 0])

[2 4 6]


In [90]:
marks = np.array([
    [80,90],
    [70,60],
    [95,85]
])

print(marks[marks > 80])

[90 95 85]


In [92]:
students = np.array([
    [101,80],
    [102,65],
    [103,90],
    [104,75]
])
#ID   Marks
print(students[students[:,1]>70])

[[101  80]
 [103  90]
 [104  75]]
