# 📘 Notebook 05 – Reshaping

## 🎯 Goal

Learn how to change the **shape (structure)** of NumPy arrays without changing the actual data.

## Topics Covered

- reshape()
- flatten()
- ravel()
- transpose()
- resize()
- squeeze()
- expand_dims()


# 📖 What is `reshape()`?

The **`reshape()`** function is used to change the **shape (dimensions)** of an existing NumPy array **without changing its data**.

It rearranges the elements into a new shape while preserving all the values.

Think of it as reorganizing books on a shelf. The books remain the same; only their arrangement changes.

Similarly, `reshape()` only changes how the data is organized, not the data itself.

In [30]:
import numpy as np

arr = np.arange(1, 13)

print("Original Array:")
print(arr)

reshaped_arr = arr.reshape(2, 2, 3)

print("\nReshaped Array:")
print(reshaped_arr)

print("\nShape:", reshaped_arr.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape: (2, 2, 3)


In [31]:
import numpy as np

arr = np.arange(1, 13)

print("Original Array:")
print(arr)

arr = arr.reshape(2, 2, 3)

print("\nReshaped Array:")
print(arr)

print("\nShape:",arr.shape)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Shape: (2, 2, 3)


In [5]:
import numpy as np
arr = np.arange(1, 13)
arr.reshape(3, -1) #Automatic dimension using -1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
import numpy as np
arr = np.arange(1, 13)
arr.reshape(-1, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
import numpy as np
arr = np.arange(1, 7)
arr.reshape(4, 2) #Error

ValueError: cannot reshape array of size 6 into shape (4,2)

In [12]:
import numpy as np
arr=np.arange(1,17)
new_arr=arr.reshape(4,4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


# 🔷 flatten()

`flatten()` is used to convert a multi-dimensional NumPy array into a **1D array**.

It returns a **new copy** of the array, so changes made to the flattened array do **not** affect the original array.

In [13]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Original Array:")
print(arr)
flatten_arr=arr.flatten()
print(flatten_arr)

Original Array:
[[10 20 30]
 [40 50 60]]
[10 20 30 40 50 60]


In [14]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()
flat[0] = 100
print("Flattened Array:")
print(flat)
print("\nOriginal Array:")
print(arr)

Flattened Array:
[100   2   3   4   5   6]

Original Array:
[[1 2 3]
 [4 5 6]]


In [16]:
import numpy as np
arr=np.arange(1,13).reshape(2,2,3)
print(arr)
flat=arr.flatten()
print(flat)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 🔷 ravel()

`ravel()` is used to convert a multi-dimensional NumPy array into a **1D array**.

Unlike `flatten()`, `ravel()` returns a **view** of the original array whenever possible, making it faster and more memory efficient.

In [17]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print("Original Array:")
print(arr)

ravel_arr = arr.ravel()

print("\nRaveled Array:")
print(ravel_arr)

print("\nShape:", ravel_arr.shape)

Original Array:
[[10 20 30]
 [40 50 60]]

Raveled Array:
[10 20 30 40 50 60]

Shape: (6,)


In [20]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
ravel=arr.ravel()
ravel[0]=100
print("Raveled Array:")
print(ravel)
print("\nOriginal Array:")
print(arr)


Raveled Array:
[100   2   3   4   5   6]

Original Array:
[[100   2   3]
 [  4   5   6]]


In [21]:
import numpy as np

arr = np.arange(1, 13).reshape(2, 2, 3)

print("Original Shape:", arr.shape)

ravel_arr = arr.ravel()

print("\nRaveled Array:")
print(ravel_arr)

print("\nNew Shape:", ravel_arr.shape)

Original Shape: (2, 2, 3)

Raveled Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

New Shape: (12,)


In [22]:
import numpy as np
arr = np.array([[1, 2],
                [3, 4]])

flat = arr.flatten()
rav = arr.ravel()

flat[0] = 100
rav[1] = 200

print("Original Array:")
print(arr)

print("\nFlatten:")
print(flat)

print("\nRavel:")
print(rav)

Original Array:
[[  1 200]
 [  3   4]]

Flatten:
[100   2   3   4]

Ravel:
[  1 200   3   4]


# 🔷 transpose()

`transpose()` is used to swap the axes (dimensions) of a NumPy array.

For a 2D array, it converts **rows into columns** and **columns into rows**.

In [25]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:")
print(arr)
print("\nOriginal Shape:", arr.shape)
transposed_arr=arr.transpose()
print("Transposed array")
print(transposed_arr)
print("\nTransposedd array shape:",transposed_arr.shape)

Original Array:
[[1 2 3]
 [4 5 6]]

Original Shape: (2, 3)
Transposed array
[[1 4]
 [2 5]
 [3 6]]

Transposedd array shape: (3, 2)


In [27]:
import numpy as np

arr = np.array([[10, 20],
                [30, 40]])

print(arr.T) # Shortcut for transpose

[[10 30]
 [20 40]]


# 🔷 resize()

`resize()` is used to change the shape **and size** of a NumPy array.

Unlike `reshape()`, `resize()` can **add or remove elements**. If new elements are needed, NumPy fills them by repeating the existing data.

In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print("Original Array:")
print(arr)

arr.resize((2, 3))

print("\nResized Array:")
print(arr)

print("\nShape:", arr.shape)

Original Array:
[1 2 3 4 5 6]

Resized Array:
[[1 2 3]
 [4 5 6]]

Shape: (2, 3)


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr.resize((3, 3))
print(arr)

[[1 2 3]
 [4 0 0]
 [0 0 0]]


In [39]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
arr.resize((2, 2))
print(arr)

[[10 20]
 [30 40]]


# 🔷 squeeze()

`squeeze()` is used to remove axes (dimensions) of size **1** from a NumPy array.

It is useful when working with arrays that contain unnecessary dimensions after reshaping or loading data.

In [41]:
import numpy as np
arr = np.array([[[10, 20, 30]]])
print("Original Shape:", arr.shape)
squeezed_arr=np.squeeze(arr)
print("\nSqueezed array:",squeezed_arr)
print("\nNew Shape:",squeezed_arr.shape)

Original Shape: (1, 1, 3)

Squeezed array: [10 20 30]

New Shape: (3,)


In [44]:
import numpy as np

arr = np.array([[[1, 2, 3]]])

print("Original Shape:", arr.shape)

new_arr = np.squeeze(arr, axis=0)

print("\nShape:", new_arr.shape)

print(new_arr)

Original Shape: (1, 1, 3)

Shape: (1, 3)
[[1 2 3]]


In [47]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

np.squeeze(arr, axis=1) #Gives Error as axes 1 has more than 1 elements

ValueError: cannot select an axis to squeeze out which has size not equal to one

# 🔷 expand_dims()

`expand_dims()` is used to add a new axis (dimension) to an existing NumPy array.

It is the opposite of `squeeze()` and is useful when preparing data for machine learning and deep learning models.

In [53]:
import numpy as np

arr = np.array([10, 20, 30])
print("Original Shape:", arr.shape)
new_arr = np.expand_dims(arr, axis=0)

print("\nNew Array:")
print(new_arr)

print("\nNew Shape:", new_arr.shape)

Original Shape: (3,)

New Array:
[[10 20 30]]

New Shape: (1, 3)


In [54]:
import numpy as np

arr = np.array([10, 20, 30])

new_arr = np.expand_dims(arr, axis=1)

print(new_arr)

print(new_arr.shape)

[[10]
 [20]
 [30]]
(3, 1)


In [55]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])

print("Original Shape:", arr.shape)

new_arr = np.expand_dims(arr, axis=2)

print("\nNew Shape:", new_arr.shape)

Original Shape: (2, 2)

New Shape: (2, 2, 1)


In [57]:
arr = np.array([10,20,30])

new_arr = arr[np.newaxis, np.newaxis, :]

print(new_arr.shape)


(1, 1, 3)
