# 🔷 Arithmetic Operations (`+`, `-`, `*`, `/`)

Arithmetic operations perform element-wise calculations on NumPy arrays or between an array and a scalar.

The arrays must have compatible shapes (broadcasting rules apply).

In [1]:
import numpy as np

arr = np.array([10, 20, 30])

print("Addition:", arr + 5)
print("Subtraction:", arr - 5)
print("Multiplication:", arr * 5)
print("Division:", arr / 5)

Addition: [15 25 35]
Subtraction: [ 5 15 25]
Multiplication: [ 50 100 150]
Division: [2. 4. 6.]


In [2]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]
Division: [10. 10. 10.]


In [3]:
import numpy as np

a = np.array([[2, 4],
              [6, 8]])

b = np.array([[1, 2],
              [3, 4]])

print("Addition:")
print(a + b)

print("\nMultiplication:")
print(a * b)

Addition:
[[ 3  6]
 [ 9 12]]

Multiplication:
[[ 2  8]
 [18 32]]


# 🔷 Universal Functions (ufuncs)

Universal functions (ufuncs) are built-in NumPy functions that perform operations element-wise on arrays.

They are fast, optimized, and work on arrays of any shape.

In [7]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(np.add(a, b))
print(np.multiply(a, b))

[11 22 33]
[10 40 90]


# 🔷 sqrt()

`sqrt()` returns the square root of each element in a NumPy array.

Negative numbers produce `nan` (Not a Number) for real-valued arrays.

In [16]:
import numpy as np

arr = np.array([1, 4, 9, 16, 25])
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


In [15]:
import numpy as np

arr = np.array([0, 36, 49, 64])
print(np.sqrt(arr))

[0. 6. 7. 8.]


In [14]:
import numpy as np

arr = np.array([4, 9, -16, 25])
print(np.sqrt(arr)) # -16 sqrt not allowed

[ 2.  3. nan  5.]


C:\Users\armaa\AppData\Local\Temp\ipykernel_14748\820076630.py:4: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(arr)) # -16 sqrt not allowed


# 🔷 power()

`power()` raises each element of an array to the given exponent.

It performs element-wise exponentiation and supports arrays or scalars as exponents.

In [13]:
import numpy as np

arr = np.array([2, 3, 4])
print(np.power(arr, 2))
print(np.power(arr, 3))

[ 4  9 16]
[ 8 27 64]


In [17]:
import numpy as np

base = np.array([2, 3, 4])
exponent = np.array([3, 2, 1])
print(np.power(base, exponent))

[8 9 4]


# 🔷 abs()

`abs()` returns the absolute (positive) value of each element in a NumPy array.

Negative numbers become positive, while positive numbers and zero remain unchanged.

In [18]:
import numpy as np

arr = np.array([-10, -5, 0, 5, 10])
print(np.abs(arr))

[10  5  0  5 10]


In [19]:
import numpy as np

arr = np.array([-2.5, 3.8, -7.1])
print(np.abs(arr))

[2.5 3.8 7.1]


In [20]:
import numpy as np

arr = np.array([[-1, 2],
                [-3, 4]])

print(np.abs(arr))

[[1 2]
 [3 4]]


# 🔷 exp()

`exp()` calculates the exponential value (eˣ) of each element in a NumPy array.

It returns \(e\) raised to the power of every element, where \(e \approx 2.71828\).

In [21]:
import numpy as np

arr = np.array([0, 1, 2])
print(np.exp(arr))

[1.         2.71828183 7.3890561 ]


In [22]:
import numpy as np

arr = np.array([-1, 0, 1])
print(np.exp(arr))

[0.36787944 1.         2.71828183]


In [23]:
import numpy as np

arr = np.array([[0, 1],
                [2, 3]])

print(np.exp(arr))

[[ 1.          2.71828183]
 [ 7.3890561  20.08553692]]


# 🔷 log()

`log()` computes the natural logarithm (base e) of each element in a NumPy array.

The input values must be positive. `log(0)` gives `-inf` and negative values produce `nan`.

In [24]:
import numpy as np

arr = np.array([1, np.e, np.e**2])
print(np.log(arr))

[0. 1. 2.]


In [29]:
import numpy as np

arr = np.array([1, 10, 100])
print(np.log(arr)) # It is log base e
print(np.log10(arr))

[0.         2.30258509 4.60517019]
[0. 1. 2.]


In [30]:
import numpy as np

arr = np.array([1, 0, -5])
print(np.log(arr))

[  0. -inf  nan]


C:\Users\armaa\AppData\Local\Temp\ipykernel_14748\809847725.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))
C:\Users\armaa\AppData\Local\Temp\ipykernel_14748\809847725.py:4: RuntimeWarning: invalid value encountered in log
  print(np.log(arr))


# 🔷 sin()

`sin()` computes the sine of each angle in a NumPy array.

The input angles must be in **radians**, not degrees.

In [34]:
import numpy as np

angles = np.array([0, np.pi/2, np.pi])
result = np.sin(angles)
print(np.round(result, 2))

[0. 1. 0.]


In [33]:
import numpy as np

angles = np.array([30, 45, 90])
radians = np.deg2rad(angles)
print(np.sin(radians))

[0.5        0.70710678 1.        ]


# 🔷 cos()

`cos()` computes the cosine of each element in a NumPy array.

The input values must be in **radians**, not degrees.

In [35]:
import numpy as np

angles = np.array([0, np.pi/2, np.pi])
print(np.cos(angles))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]


In [36]:
import numpy as np

angles = np.array([0, 30, 60, 90])
radians = np.deg2rad(angles)
print(np.cos(radians))

[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]


In [37]:
import numpy as np

angles = np.linspace(0, np.pi, 5)
print(np.round(np.cos(angles), 2))

[ 1.    0.71  0.   -0.71 -1.  ]


# 🔷 tan()

`tan()` computes the tangent of each element in a NumPy array.

Input must be in **radians**, not degrees.

In [38]:
import numpy as np

angles = np.array([0, np.pi/4, np.pi/2])
print(np.tan(angles))

[0.00000000e+00 1.00000000e+00 1.63312394e+16]


In [39]:
import numpy as np

angles = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(angles)
print(np.round(np.tan(radians), 2))

[0.00000000e+00 5.80000000e-01 1.00000000e+00 1.73000000e+00
 1.63312394e+16]


In [41]:
import numpy as np

x = np.linspace(0, np.pi/2, 5)
print(np.round(np.tan(x), 2))

[0.00000000e+00 4.10000000e-01 1.00000000e+00 2.41000000e+00
 1.63312394e+16]
