# 🔷 Broadcasting

Broadcasting allows NumPy to perform element-wise operations on arrays of different shapes by automatically expanding the smaller array.

The arrays must satisfy NumPy's broadcasting rules to be compatible.

In [1]:
import numpy as np

a = np.array([10, 20, 30])
print(a + 5)

[15 25 35]


In [5]:
import numpy as np

a = np.array([[1],
              [2],
              [3]])

b = np.array([10, 20, 30])

print(a)
print(a.shape)

print("\n",b)
print(b.shape)

print(a + b)

[[1]
 [2]
 [3]]
(3, 1)

 [10 20 30]
(3,)
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [6]:
import numpy as np

a = np.array([[1, 2, 3]])

b = np.array([[10],
              [20]])

print(a.shape)
print(b.shape)

print(a + b)

(1, 3)
(2, 1)
[[11 12 13]
 [21 22 23]]


In [7]:
import numpy as np

a = np.array([[1],
              [2],
              [3]])

b = np.array([10, 20, 30])

print(a.shape)
print(b.shape)

print(a + b)

(3, 1)
(3,)
[[11 21 31]
 [12 22 32]
 [13 23 33]]


# 🔷 Broadcasting Rules

NumPy follows these three rules to determine whether two arrays can be broadcast together.

### Rule 1
If the arrays have different numbers of dimensions, NumPy adds dimensions of size **1** to the **left** of the smaller-dimensional array.

### Rule 2
Starting from the **rightmost dimension**, NumPy compares the dimensions. Broadcasting is possible only if:
- The dimensions are equal, or
- One of the dimensions is **1**.

Otherwise, broadcasting fails.

### Rule 3
If a dimension is **1**, NumPy automatically expands (broadcasts) it to match the corresponding dimension of the other array.

**Note:** Broadcasting is virtual. NumPy does **not** create a physical copy of the data.

In [8]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10, 20],
              [30, 40]])

print("a shape:", a.shape)
print("b shape:", b.shape)

print(a + b)

a shape: (2, 3)
b shape: (2, 2)


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [9]:
import numpy as np

marks = np.array([65, 72, 81, 90])
bonus = 5
final_marks = marks + bonus
print(final_marks)

[70 77 86 95]


In [10]:
import numpy as np

prices = np.array([100, 250, 400, 150])
discount = 0.10
final_prices = prices - (prices * discount)
print(final_prices)

[ 90. 225. 360. 135.]


# 🔷 Common Errors

Broadcasting fails when two arrays have incompatible shapes.

The most common error is `ValueError: operands could not be broadcast together`.

In [11]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([10, 20])
print(a + b)

ValueError: operands could not be broadcast together with shapes (3,) (2,) 