# 🔷 sum()

`sum()` is used to calculate the total of array elements.

It can calculate the sum of the entire array or along a specific axis.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(np.sum(arr))

100


In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(np.sum(arr))

21


In [4]:
import numpy as np

sales = np.array([100, 150, 200, 250])
total_sales = np.sum(sales)
print(total_sales)

700


# 🔷 mean()

`mean()` is used to calculate the average (arithmetic mean) of array elements.

It returns the sum of all elements divided by the total number of elements.

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(np.mean(arr))

25.0


In [8]:
import numpy as np

arr = np.array([[2, 4],
                [6, 8]])
print(arr.shape)
print(np.mean(arr))


(2, 2)
5.0


In [9]:
import numpy as np

marks = np.array([78, 85, 92, 95])
average_marks = np.mean(marks)
print(average_marks)

87.5


# 🔷 median()

`median()` returns the middle value of a sorted array.

If the array has an even number of elements, it returns the average of the two middle values.

In [11]:
import numpy as np

arr=np.array([10,20,30,40,50]) 
print(np.median(arr))

30.0


In [12]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(np.median(arr))

25.0


In [13]:
import numpy as np

arr = np.array([40, 10, 50, 20, 30])
print(np.median(arr))

30.0


# 🔷 std()

`std()` calculates the standard deviation of array elements.

It measures how much the values are spread out from the mean.

In [14]:
import numpy as np

arr = np.array([10, 10, 10, 10])
print(np.std(arr))

0.0


In [15]:
import numpy as np

arr = np.array([2, 4, 6, 8])
print(np.std(arr))

2.23606797749979


In [19]:
import numpy as np

marks = np.array([78, 80, 82, 79, 81])
print(np.round(np.std(marks), 3))

1.414


# 🔷 var()

`var()` calculates the variance of array elements.

Variance measures how far the values are spread from the mean. It is the square of the standard deviation.

In [20]:
import numpy as np

arr = np.array([10, 10, 10, 10])
print(np.var(arr))

0.0


In [21]:
import numpy as np

marks = np.array([78, 80, 82, 79, 81])
print(np.round(np.var(marks), 2))

2.0


# 🔷 min()

`min()` returns the smallest element in a NumPy array.

If no axis is specified, it finds the minimum from the entire array.

In [23]:
import numpy as np

arr = np.array([12, 5, 18, 9])
print(np.min(arr))

5


In [24]:
import numpy as np

arr = np.array([25, -10, 40, 15])
print(np.min(arr))

-10


In [25]:
import numpy as np

temperatures = np.array([32, 28, 35, 30, 27])
lowest = np.min(temperatures)
print(lowest)

27


# 🔷 max()

`max()` returns the largest element in a NumPy array.

If no axis is specified, it finds the maximum from the entire array.

In [26]:
import numpy as np

arr = np.array([12, 5, 18, 9])
print(np.max(arr))

18


In [27]:
import numpy as np

arr = np.array([-10, 25, 40, 15])
print(np.max(arr))

40


In [28]:
import numpy as np

sales = np.array([1200, 1800, 950, 2100, 1750])
max_sales=np.max(sales)
print(max_sales)

2100


# 🔷 argmin()

`argmin()` returns the index of the smallest element in a NumPy array.

It returns the position, not the value.

In [30]:
import numpy as np

arr = np.array([12, 5, 18, 9])
print(np.argmin(arr))

1


In [31]:
import numpy as np

arr = np.array([25, -10, 40, 15])
print(np.argmin(arr))

1


In [37]:
import numpy as np

marks = np.array([78, 92, 65, 88, 95])
lowest_index = np.argmin(marks)
print(lowest_index)
print(marks[lowest_index])

2
65


# 🔷 argmax()

`argmax()` returns the index of the largest element in a NumPy array.

It returns the position, not the value.

In [38]:
import numpy as np

arr = np.array([12, 5, 18, 9])
print(np.argmax(arr))

2


In [39]:
import numpy as np

arr = np.array([25, -10, 40, 15])
print(np.argmax(arr))

2


In [40]:
import numpy as np

marks = np.array([78, 92, 65, 88, 95])
highest_index = np.argmax(marks)
print(highest_index)
print(marks[highest_index])

4
95


# 🔷 Axis Operations

The `axis` parameter tells NumPy along which direction to perform an operation.

`axis=0` works column-wise, while `axis=1` works row-wise.

In [44]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [46]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(np.mean(arr, axis=0))
print(np.mean(arr, axis=1))
print(np.mean(arr))

[25. 35. 45.]
[20. 50.]
35.0


The axis parameter is supported by almost all NumPy aggregation functions:

np.sum()

np.mean()

np.median()

np.std()

np.var()

np.min()

np.max()

np.argmin()

np.argmax()

# 🔷 cumsum()

`cumsum()` returns the cumulative (running) sum of array elements.

Each element is the sum of itself and all previous elements.

In [47]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(np.cumsum(arr))

[ 1  3  6 10]


In [48]:
import numpy as np

sales = np.array([100, 200, 150, 250])
print(np.cumsum(sales))

[100 300 450 700]


In [55]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])
print(np.cumsum(arr))
print(np.cumsum(arr,axis=0))
print(np.cumsum(arr,axis=1))

[ 1  3  6 10]
[[1 2]
 [4 6]]
[[1 3]
 [3 7]]


# 🔷 cumprod()

`cumprod()` returns the cumulative (running) product of array elements.

Each element is multiplied with all previous elements.

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(np.cumprod(arr))

[ 1  2  6 24]


In [51]:
import numpy as np

arr = np.array([2, 3, 4])
print(np.cumprod(arr))

[ 2  6 24]


In [57]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])
print(np.cumprod(arr))
print(np.cumprod(arr,axis=0))
print(np.cumprod(arr,axis=1))

[ 1  2  6 24]
[[1 2]
 [3 8]]
[[ 1  2]
 [ 3 12]]
