# 🔷 Random module()
# 🔷 rand()

`rand()` generates random numbers between **0 (inclusive)** and **1 (exclusive)**.

It returns floating-point numbers and is useful for creating random datasets.

In [8]:
import numpy as np 
print(np.random.rand())

0.6459184320161069


In [7]:
import numpy as np
print(np.random.rand(5))

[0.13335204 0.89505896 0.27036241 0.05858435 0.52319922]


In [9]:
import numpy as np
print(np.random.rand(2,3))

[[0.62333343 0.64590149 0.83218223]
 [0.61453938 0.71789779 0.0836414 ]]


# 🔷 randint()

`randint()` generates random integers within a given range.

The starting value is included, but the ending value is excluded.

In [10]:
import numpy as np
print(np.random.randint(1,10))

4


In [12]:
import numpy as np
print(np.random.randint(1,10,size=5))

[1 8 8 9 9]


In [13]:
import numpy as np
print(np.random.randint(1,10,size=(2,5)))

[[6 7 5 6 4]
 [1 6 4 2 9]]


# 🔷 randn()

`randn()` generates random numbers from the **standard normal (Gaussian) distribution**.

The values are centered around **0** and can be positive or negative.

In [14]:
import numpy as np 
print(np.random.randn())

0.079670713341299


In [16]:
import numpy as np
print(np.random.randn(5))

[-0.59899804 -0.60752714  0.31827077  0.49024366  0.28856011]


In [18]:
import numpy as np
print(np.random.randn(2,4))

[[-1.18493769 -0.27953332 -0.0206128   1.3014431 ]
 [-1.21964583 -2.177843   -0.33521004 -1.54048348]]


# 🔷 choice()

`choice()` randomly selects one or more elements from an array or list.

It can select with or without replacement.

In [19]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr))

20


In [20]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr,size=3))

[50 20 20]


In [21]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr,size=3,replace=False))

#replace=False means without replacement.
#Once an element is selected, it cannot be selected again.
#Therefore, all selected values are unique.

[50 30 10]


In [22]:
import numpy as np

arr = np.array([1, 2, 3])

print(np.random.choice(arr, size=5, replace=False))

ValueError: Cannot take a larger sample than population when 'replace=False'

In [23]:
import numpy as np

arr = np.array([1, 2, 3])

print(np.random.choice(arr, size=5))

[3 3 2 3 2]


# 🔷 shuffle()

`shuffle()` randomly rearranges the elements of an array.

It modifies the original array (in-place) and does not create a new one.

In [27]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
np.random.shuffle(arr)
print(arr)

[50 20 30 10 40]


In [29]:
import numpy as np

arr = np.array(["A", "B", "C", "D"])
np.random.shuffle(arr)
print(arr)

['D' 'C' 'A' 'B']


In [30]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
np.random.shuffle(arr)
print(arr)
#For a 2D array, shuffle() shuffles the rows, not the individual elements.
#he values inside each row remain together.

[[1 2]
 [5 6]
 [3 4]]


# 🔷 permutation()

`permutation()` returns a randomly shuffled copy of an array.

Unlike `shuffle()`, it does **not** modify the original array.

In [31]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
new_arr = np.random.permutation(arr)
print(new_arr)
print(arr)

[40 50 10 30 20]
[10 20 30 40 50]


In [33]:
import numpy as np

arr = np.array(["A", "B", "C", "D"])
print(np.random.permutation(arr))
print(arr)

['D' 'A' 'C' 'B']
['A' 'B' 'C' 'D']


In [34]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print(np.random.permutation(arr))


[[3 4]
 [1 2]
 [5 6]]


# 🔷 seed()

`seed()` sets the starting point for NumPy's random number generator.

Using the same seed produces the same random numbers every time.

In [70]:
import numpy as np
np.random.seed(10)
print(np.random.rand(3))

[0.77132064 0.02075195 0.63364823]


In [82]:
import numpy as np

np.random.seed(20)
print(np.random.rand(3))

[0.5881308  0.89771373 0.89153073]


In [92]:
import numpy as np

np.random.seed(10)
print(np.random.rand())
print(np.random.rand())
print(np.random.rand())

0.771320643266746
0.0207519493594015
0.6336482349262754


In [100]:
import numpy as np

np.random.seed(10)
print(np.random.rand(3))
print(np.random.rand(3))

[0.77132064 0.02075195 0.63364823]
[0.74880388 0.49850701 0.22479665]
