# 📘 10_Boolean_Masking

# 🔷 comparisons

Comparison operators compare each element of a NumPy array with a value or another array.

The result is a Boolean array containing True or False.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result=arr>25
print(result)

[False False  True  True  True]


In [6]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25])
result=arr==15
print(result)
print(np.where(result))


[False False  True False False]
(array([2]),)


In [5]:
import numpy as np

arr1 = np.array([5, 8, 12, 18])
arr2 = np.array([4, 8, 15, 10])
result = arr1 >= arr2
print(result)

[ True  True False  True]


# 🔷 boolean arrays

A Boolean array is a NumPy array whose elements are only `True` or `False`.

It is commonly created using comparison operations and is used for filtering data.

In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40])
mask = arr> 20
print(mask)

[False False  True  True]


In [8]:
import numpy as np

arr = np.array([5, 10, 15, 20, 25])
result= (arr>=10)&(arr<=20)
print(result)

[False  True  True  True False]


# 🔷 filtering datasets

Boolean arrays can be used to select only the elements where the condition is `True`.

This technique is called Boolean Masking or Filtering.

In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result= arr[arr>25]
print(result)

[30 40 50]


In [14]:
import numpy as np

arr = np.array([45, 80, 65, 90, 30])
result=arr[arr>=50]
print(result)

[80 65 90]


In [15]:
import numpy as np

arr = np.array([5, 12, 18, 25, 30, 40])
result = arr[(arr >= 10) & (arr <= 30)]
print(result)

[12 18 25 30]


# 🔷 where()

where() returns the indices of elements that satisfy a condition.

It can also be used to replace values based on a condition.

In [16]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result= np.where(arr > 25)
print(result)

(array([2, 3, 4]),)


In [20]:
import numpy as np

arr = np.array([12, 15, 18, 21, 24])
result=np.where(arr % 2==0)
print(result)

(array([0, 2, 4]),)


In [23]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr >= 30, "Pass", "Fail")
print(result)

['Fail' 'Fail' 'Pass' 'Pass' 'Pass']


# 🔷 any()

any() checks whether at least one element in a NumPy array is `True`.

It returns a single Boolean value: `True` or `False`.

In [24]:
import numpy as np

arr = np.array([False, False, True, False])
result=np.any(arr)
print(result)

True


In [26]:
import numpy as np

arr = np.array([10, 20, 30, 40])
result = np.any(arr > 35)
print(result)

True


In [27]:
import numpy as np

arr = np.array([5, 10, 15])
result = np.any(arr > 20)
print(result)

False


# 🔷 all()

all() checks whether every element in a NumPy array is `True`.

It returns a single Boolean value: `True` only if all elements satisfy the condition.

In [28]:
import numpy as np

arr = np.array([True, True, True])
result = np.all(arr)
print(result)

True


In [29]:
import numpy as np
arr = np.array([10, 20, 30, 40])
result = np.all(arr > 5)
print(result)

True


In [30]:
import numpy as np

arr = np.array([10, 20, 30, 40])
result = np.all(arr > 20)
print(result)

False


# 📝 Quick Revision Sheet

| Function | Purpose | Returns |
|----------|---------|---------|
| Comparison (`>`, `<`, `==`, `!=`) | Compare elements | Boolean array |
| Boolean Array | Stores `True` / `False` values | `dtype=bool` |
| `arr[mask]` | Filter values using a Boolean mask | Matching values |
| `np.where(condition)` | Find indices satisfying a condition | Indices |
| `np.where(condition, x, y)` | Vectorized if-else | New array |
| `np.any()` | Checks if **at least one** element is `True` | `True` / `False` |
| `np.all()` | Checks if **all** elements are `True` | `True` / `False` |
