# 📘 11_Sorting_Searching_Unique

# 🔷 sort()

sort() returns a sorted copy of a NumPy array.

By default, it sorts the array in ascending order without changing the original array.

In [2]:
import numpy as np

arr = np.array([8, 3, 1, 6, 4])
result=np.sort(arr)
print("Original Array:" ,arr)
print("Sorted Array:", result)

Original Array: [8 3 1 6 4]
Sorted Array: [1 3 4 6 8]


In [3]:
import numpy as np

arr = np.array([[7, 2, 5],
                [9, 1, 3]])
result = np.sort(arr)
print(result)

[[2 5 7]
 [1 3 9]]


In [4]:
import numpy as np

arr = np.array([[7, 2, 5],
                [9, 1, 3]])
result = np.sort(arr, axis=0)
print(result)

[[7 1 3]
 [9 2 5]]


In [10]:
import numpy as np

arr = np.array([8, 3, 1, 6, 4])
print(np.sort(arr))
print(np.sort(arr)[::-1])


[1 3 4 6 8]
[8 6 4 3 1]


# 🔷 argsort()

argsort() returns the indices that would sort an array.

It tells you the positions of elements in sorted order instead of returning the sorted values.

In [11]:
import numpy as np

arr = np.array([50, 20, 40, 10, 30])
result =np.argsort(arr)
print(result)

[3 1 4 2 0]


In [12]:
import numpy as np

arr = np.array([50, 20, 40, 10, 30])
sorted_arr = arr[np.argsort(arr)]
print(sorted_arr)

[10 20 30 40 50]


In [13]:
import numpy as np

names = np.array(["Rahul", "Amit", "Neha", "Priya"])
marks = np.array([75, 92, 68, 85])
index = np.argsort(marks)
print(index)
print(names[index])
print(marks[index])

[2 0 3 1]
['Neha' 'Rahul' 'Priya' 'Amit']
[68 75 85 92]


# 🔷 searchsorted()

searchsorted() finds the index where a value should be inserted in a sorted array to maintain the sorted order.

The array must be sorted before using `searchsorted()`.

In [14]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result=np.searchsorted(arr,35)
print(result)

3


In [15]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = np.searchsorted(arr, 30)
print(result)

2


In [16]:
import numpy as np

arr = np.array([10, 20, 20, 20, 30, 40])

left = np.searchsorted(arr, 20, side="left")
right = np.searchsorted(arr, 20, side="right")

print("Left :", left)
print("Right:", right)

Left : 1
Right: 4


In [17]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
values = [15, 35, 55]
result = np.searchsorted(arr, values)
print(result)

[1 3 5]


# 🔷 unique()

unique() returns the unique (distinct) elements from a NumPy array.

The returned values are sorted in ascending order.

In [18]:
import numpy as np

arr = np.array([10, 20, 10, 30, 20, 40])
result= np.unique(arr)
print(result)

[10 20 30 40]


In [19]:
import numpy as np

arr = np.array([5, 2, 8, 2, 5, 1])
result = np.unique(arr)
print(result)

[1 2 5 8]


In [20]:
import numpy as np

arr = np.array(["Apple", "Banana", "Apple", "Mango", "Banana"])
result = np.unique(arr)
print(result)

['Apple' 'Banana' 'Mango']


In [21]:
import numpy as np

arr = np.array([10, 20, 10, 30, 20, 40])
unique_values,counts=np.unique(arr,return_counts=True)
print("Unique Values:",unique_values)
print("Counts:",counts)

Unique Values: [10 20 30 40]
Counts: [2 2 1 1]


# 🔷 isin()

isin() checks whether each element of an array exists in another array.

It returns a Boolean array containing `True` or `False`.

In [22]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = np.isin(arr, [20, 40])
print(result)

[False  True False  True False]


In [23]:
import numpy as np

students = np.array(["Rahul", "Amit", "Neha", "Priya"])
present = np.array(["Amit", "Priya"])
result = np.isin(students, present)
print(result)

[False  True False  True]


In [24]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = arr[np.isin(arr, [20, 40])]
print(result)

[20 40]


In [25]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = arr[~np.isin(arr, [20, 40])]
print(result)

[10 30 50]


# 📝 Quick Revision Sheet

| Function | Purpose | Returns |
|----------|---------|---------|
| `np.sort()` | Sort values | New sorted array |
| `np.argsort()` | Get sorted indices | Indices |
| `np.searchsorted()` | Find insertion position | Index/Indices |
| `np.unique()` | Remove duplicates | Sorted unique values |
| `np.unique(return_counts=True)` | Count frequencies | Values + Counts |
| `np.isin()` | Membership check | Boolean array |