# 📘 12_Stacking_Splitting_Copy_View

# 🔷 concatenate()

concatenate() joins two or more NumPy arrays along an existing axis.

The arrays must have compatible shapes except for the joining axis.

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))

print(result)

[1 2 3 4 5 6]


In [2]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.concatenate((arr1, arr2), axis=0)

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.concatenate((arr1, arr2), axis=1)

print(result)

[[1 2 5 6]
 [3 4 7 8]]


# 🔷 stack()

stack() joins multiple arrays by adding a new axis.

Unlike concatenate(), stack() increases the dimension of the array.

In [5]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.stack((arr1, arr2))

print(result)
print(np.shape(result))

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.stack((arr1, arr2), axis=1)

print(result)

[[1 4]
 [2 5]
 [3 6]]


In [7]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.stack((arr1, arr2))

print(result)
print(result.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


# 🔷 hstack()

hstack() stacks arrays horizontally.

It joins arrays column-wise and is a shortcut for horizontal stacking.

In [8]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.hstack((arr1, arr2))

print(result)

[1 2 3 4 5 6]


In [9]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.hstack((arr1, arr2))

print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [13]:
import numpy as np

arr1 = np.array([[10],
                 [20],
                 [30]])

arr2 = np.array([[40],
                 [50],
                 [60]])

result = np.hstack((arr1, arr2))

print(result)

[[10 40]
 [20 50]
 [30 60]]


# 🔷 vstack()

vstack() stacks arrays vertically.

It joins arrays row-wise by adding rows below each other.

In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))

print(result)

[[1 2 3]
 [4 5 6]]


In [19]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.vstack((arr1, arr2))

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
import numpy as np

arr1 = np.array([[10, 20, 30]])
arr2 = np.array([[40, 50, 60]])
result = np.vstack((arr1, arr2))

print(result)

[[10 20 30]
 [40 50 60]]


# 🔷 split()

split() divides a NumPy array into multiple smaller arrays.

It is the opposite operation of concatenate().

In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
result = np.split(arr, 3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [22]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])
result = np.split(arr, [2, 5])
print(result)

[array([10, 20]), array([30, 40, 50]), array([60])]


In [23]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])

result = np.split(arr, 2, axis=0)

print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


# 🔷 hsplit()

hsplit() splits an array horizontally.

It divides an array column-wise and is mainly used with 2D arrays.

In [28]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

result = np.hsplit(arr, 2)

print(result)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [33]:
import numpy as np

arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80]])

result = np.hsplit(arr, [1, 3])

print(result)

[array([[10],
       [50]]), array([[20, 30],
       [60, 70]]), array([[40],
       [80]])]


In [38]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.hsplit(arr, 3)

for item in result:
    print(item)

[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


# 🔷 vsplit()

vsplit() splits an array vertically.

It divides an array row-wise and is mainly used with 2D arrays.

In [41]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4],
                [5, 6],
                [7, 8]])

result = np.vsplit(arr, 2)

print(result)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


In [43]:
import numpy as np

arr = np.array([[10, 20],
                [30, 40],
                [50, 60],
                [70, 80]])

result = np.vsplit(arr, [1, 3])

print(result)

[array([[10, 20]]), array([[30, 40],
       [50, 60]]), array([[70, 80]])]


In [44]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

result = np.vsplit(arr, 2)

for item in result:
    print(item)

[[1 2 3]]
[[4 5 6]]


# 🔷 copy vs view

copy creates a completely independent array.

view creates a new array that shares the same data with the original array.

In [48]:
import numpy as np

arr = np.array([1, 2, 3])
copy_arr = arr.copy()
copy_arr[0] = 100
print(arr)
print(copy_arr)

[1 2 3]
[100   2   3]


In [52]:
import numpy as np
arr = np.array([1, 2, 3])
view_arr = arr.view()
view_arr[0] = 100
print(arr)
print(view_arr)

[100   2   3]
[100   2   3]


In [47]:
import numpy as np

arr = np.array([10, 20, 30])

copy_arr = arr.copy()
view_arr = arr.view()

print(arr.base)
print(copy_arr.base)
print(view_arr.base)



None
None
[10 20 30]


.base tells whether an array is using another array's memory.

Copy has no base because it owns its data.

View has a base because it shares data with the original array.

In [53]:
import numpy as np

arr = np.array([[1, 2],
                [3, 4]])

view_arr = arr.view()

view_arr[0, 0] = 99

print(arr)
print(view_arr)

[[99  2]
 [ 3  4]]
[[99  2]
 [ 3  4]]
