# 📘 13_Linear_Algebra

# 🔷 dot()

dot() computes the dot product of two arrays.

Its behavior depends on the dimensions of the input arrays.

In [1]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.dot(arr1,arr2)
print(result)

32


In [2]:
import numpy as np
arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])
result = np.dot(arr1, arr2)
print(result)

[[19 22]
 [43 50]]


For 2D arrays, dot() performs matrix multiplication.

It multiplies rows of the first matrix with columns of the second matrix.

In [4]:
import numpy as np

arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 3, 5])
print(np.dot(arr1, arr2))

44


# 🔷 matmul()

matmul() performs matrix multiplication between two arrays.

It is specifically designed for matrix multiplication and supports higher-dimensional arrays.

In [5]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])
result=np.matmul(arr1,arr2)
print(result)

[[19 22]
 [43 50]]


In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.matmul(a, b)
print(result)

32


In [7]:
import numpy as np

a = np.array([[1, 2, 3]])

b = np.array([[4],
              [5],
              [6]])

result = np.matmul(a, b)
print(result)

[[32]]


@ operator = matmul()

A @ B is the same as: np.matmul(A, B)

# 🔷 det()

det() calculates the determinant of a square matrix.

The determinant is a single value that represents important properties of a matrix.

In [10]:
import numpy as np

matrix = np.array([[1, 2],
                   [3, 4]])

result = np.linalg.det(matrix)
print(result)

-2.0000000000000004


In [13]:
import numpy as np
matrix = np.array([[5, 0],
                   [0, 3]])

result = np.linalg.det(matrix)
print(result)

15.0


In [14]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [0, 4, 5],
                   [1, 0, 6]])
result = np.linalg.det(matrix)
print(result)

22.000000000000004


# 🔷 inv()

inv() calculates the inverse of a square matrix.

The inverse matrix multiplied with the original matrix gives the identity matrix.

In [15]:
import numpy as np

matrix = np.array([[1, 2],
                   [3, 4]])
result = np.linalg.inv(matrix)
print(result)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
import numpy as np

matrix = np.array([[5, 0],
                   [0, 2]])
inverse = np.linalg.inv(matrix)
print(inverse)

[[0.2 0. ]
 [0.  0.5]]


In [17]:
import numpy as np

matrix = np.array([[1, 2],
                   [2, 4]])
try:
    result = np.linalg.inv(matrix)
    print(result)
except Exception as e:
    print(e)

Singular matrix


# 🔷 eig()

eig() calculates the eigenvalues and eigenvectors of a square matrix.

Eigenvalues represent important properties of a matrix transformation.

In [20]:
import numpy as np

matrix = np.array([[2, 0],
                   [0, 3]])

values, vectors = np.linalg.eig(matrix)
print(values)
print(vectors)

[2. 3.]
[[1. 0.]
 [0. 1.]]


In [23]:
import numpy as np

matrix = np.array([[4, 0],
                   [0, 2]])

eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[4. 2.]
[[1. 0.]
 [0. 1.]]


In [24]:
import numpy as np

matrix = np.array([[1, 2],
                   [2, 1]])
values, vectors = np.linalg.eig(matrix)
print(values)

[ 3. -1.]
