# 📘 14_Statistics

# 🔷 percentile()

percentile() finds the value below which a given percentage of data falls.

It helps understand the distribution and position of values in a dataset.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = np.percentile(arr, 50)
print(result)

30.0


In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.percentile(arr, 25))
print(np.percentile(arr, 75))

20.0
40.0


25th percentile (Q1) → 25% of values are below it.

75th percentile (Q3) → 75% of values are below it.

In [3]:
import numpy as np

marks = np.array([45, 50, 55, 60, 65, 70, 75])
print(np.percentile(marks,90))

72.0


In [5]:
import numpy as np

marks = np.array([45, 50, 55, 60, 65, 70, 75])
p80 = np.percentile(marks, 80)
print(p80)

69.0


# 🔷 quantile()

quantile() returns the value below which a given fraction of the data lies.

A quantile is similar to a percentile but uses values between 0 and 1.

In [6]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
result = np.quantile(arr, 0.5)
print(result)

30.0


0.5 means 50% of the data.

So, 0.5 quantile is the median.

Think of it as:

In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(np.quantile(arr, 0.25))
print(np.quantile(arr, 0.75))

20.0
40.0


In [8]:
import numpy as np

marks = np.array([45, 50, 55, 60, 65, 70, 75])
q90 = np.quantile(marks, 0.9)
print(q90)

72.0


# 🔷 cov()

cov() calculates the covariance between two or more variables.

Covariance tells whether variables tend to increase or decrease together.

In [9]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

result = np.cov(x, y)
print(result)

[[ 2.5  5. ]
 [ 5.  10. ]]


np.cov() returns a covariance matrix.

The diagonal values are the variances of each variable.

The off-diagonal values are the covariance between the variables.

     x      y          
x           variance   covariance

y           covariance   variance

In [10]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 8, 6, 4, 2])

print(np.cov(x, y))

[[ 2.5 -5. ]
 [-5.  10. ]]


In [11]:
import numpy as np

hours = np.array([2, 4, 6, 8])
marks = np.array([40, 55, 70, 85])

cov_matrix = np.cov(hours, marks)

print(cov_matrix)

[[  6.66666667  50.        ]
 [ 50.         375.        ]]


# 🔷 corrcoef()

corrcoef() calculates the correlation between two or more variables.

Correlation tells both the direction and the strength of a linear relationship.

In [15]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

result = np.corrcoef(x, y)

print(result)

[[1. 1.]
 [1. 1.]]


np.corrcoef() returns a correlation matrix.

Correlation values are always between -1 and 1.

Here, x and y have a perfect positive correlation.

In [22]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 8, 6, 4, 2])
print(np.corrcoef(x, y))

[[ 1. -1.]
 [-1.  1.]]


In [25]:
import numpy as np

hours = np.array([2, 4, 6, 8, 10])
marks = np.array([35, 50, 60, 75, 90])

corr = np.corrcoef(hours, marks)
print(corr)

[[1.         0.99794872]
 [0.99794872 1.        ]]


# 🔷 histogram()

histogram() counts how many values fall into different ranges (called bins).

It helps understand how data is distributed.

In [1]:
import numpy as np

arr = np.array([1, 2, 2, 3, 3, 3, 4, 5])
counts,bins=np.histogram(arr)
print(counts)
print(bins)

[1 0 2 0 0 3 0 1 0 1]
[1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6 5. ]


np.histogram() returns two arrays:

counts → Number of values in each bin.

bins → The bin boundaries.

By default, NumPy creates 10 equal-width bins.

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
count,bins=np.histogram(arr,bins=5)
print(count)
print(bins)

[1 1 1 1 1]
[10. 18. 26. 34. 42. 50.]


In [3]:
import numpy as np

marks = np.array([35, 42, 48, 55, 61, 67, 73, 81, 89, 95])
count,bins=np.histogram(marks,bins=[0, 40, 60, 80, 100])
print(count)
print(bins)
                    

[1 3 3 3]
[  0  40  60  80 100]
