# 📘 15_File_IO

# 🔷 save()

save() stores a NumPy array in a binary file with the `.npy` extension.

It is the fastest and most reliable way to save NumPy arrays.

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
np.save("numbers.npy",arr)
print("Array Saved Successfully !")

Array Saved Successfully !


np.save() creates a file named numbers.npy.

.npy is NumPy's native file format.

It preserves:

Data values    

Shape     

Data type (dtype)

In [2]:
import numpy as np

marks = np.array([85, 90, 78, 92])
np.save("marks.npy",marks)
print("Saved Successfully !")

Saved Successfully !


In [3]:
import numpy as np

data = np.array([[1, 2, 3],
                 [4, 5, 6]])

np.save("matrix.npy", data)
print("Matrix saved successfully!")

Matrix saved successfully!


# 🔷 load()

load() reads a previously saved `.npy` file and returns it as a NumPy array.

It is used together with `save()`.

In [4]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
np.save("numbers.npy",arr)
loaded_arr=np.load("numbers.npy")
print(loaded_arr)

[10 20 30 40 50]


In [5]:
import numpy as np

matrix = np.array([[1, 2],
                   [3, 4]])

np.save("matrix.npy", matrix)
loaded_matrix = np.load("matrix.npy")
print(loaded_matrix)
print(loaded_matrix.shape)

[[1 2]
 [3 4]]
(2, 2)


In [6]:
import numpy as np

data = np.load("numbers.npy")
print(type(data))
print(data.dtype)

<class 'numpy.ndarray'>
int64


# 🔷 savetxt()

savetxt() saves a NumPy array as a text file such as `.txt` or `.csv`.

The saved file can be opened in Notepad, Excel, or VS Code.

In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
np.savetxt("numbers.txt",arr)
print("Saved Successfully")

Saved Successfully


np.savetxt() saves the array as a plain text file.
Contents of numbers.txt:

1.000000000000000000e+01

2.000000000000000000e+01

3.000000000000000000e+01

4.000000000000000000e+01

5.000000000000000000e+01

That's NumPy's default scientific notation.

In [8]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
np.savetxt("numbers.txt",arr,fmt="%d")
print("File saved successfully !")

File saved successfully !


fmt="%d" tells NumPy to save integers normally.

Common formats:

%d → Integer

%.2f → Float with 2 decimal places

%s → String

In [9]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
np.savetxt("matrix.csv",matrix,fmt="%d",delimiter=",")
print("CSV File created Successfully!")

CSV File created Successfully!


delimiter="," separates values with commas.

In [10]:
import numpy as np

arr = np.array([
    [101, 85],
    [102, 90],
    [103, 78]
])

np.savetxt(
    "marks.csv",
    arr,
    fmt="%d",
    delimiter=",",
    header="Student_ID,Marks"
    #comments=""  "used To remove the Hashtag from the header in Csv File" 
)

# 🔷 loadtxt()

loadtxt() reads data from a text file (`.txt` or `.csv`) and converts it into a NumPy array.

It is commonly used to load simple numeric datasets.

By default, it returns floating-point numbers (float64), even if the file contains integers.

In [11]:
import numpy as np

arr = np.loadtxt("numbers.txt")
print(arr)

[10. 20. 30. 40. 50.]


In [12]:
import numpy as np

arr = np.loadtxt("numbers.txt", dtype=int)
print(arr)
print(arr.dtype)

[10 20 30 40 50]
int64


# 🔷 CSV Handling

In [14]:
import numpy as np

students = np.array([
    [101, 85],
    [102, 90],
    [103, 78]
])

print(students)

[[101  85]
 [102  90]
 [103  78]]


In [17]:
np.savetxt(
    "students.csv",
    students,
    fmt="%d",
    delimiter=",",
    header="Student_ID,Marks",
    comments=""
)

In [19]:
students = np.loadtxt(
    "students.csv",
    delimiter=",",
    skiprows=1,  #Ignore the first row as it is text not numbers ("Student_ID,Marks")
    dtype=int
)

print(students)

[[101  85]
 [102  90]
 [103  78]]


In [20]:
print(students[:, 1])

[85 90 78]


In [21]:
print(np.mean(students[:, 1]))

84.33333333333333


In [22]:
print(np.max(students[:, 1]))

90


In [23]:
print(students[:, 0])

[101 102 103]
