## Dataset Description

In this notebook, we'll work with a **sample Employee Performance Dataset** to simulate a real-world Data Science workflow using **NumPy**.

Each row represents one employee, and each column contains a specific attribute about that employee.

| Column | Description |
|--------|-------------|
| Employee_ID | Unique ID assigned to each employee |
| Age | Employee's age (in years) |
| Department | Department code where the employee works |
| Experience | Total years of work experience |
| Salary | Monthly salary (₹) |
| Sales | Monthly sales generated (₹) |
| Rating | Performance rating (1–5) |

### Department Codes

| Code | Department |
|------|------------|
| 1 | Sales |
| 2 | Marketing |
| 3 | Human Resources (HR) |
| 4 | Information Technology (IT) |

### Business Objective

Imagine you are working as a **Junior Data Analyst** in a retail company. Your manager has asked you to analyze this employee dataset and answer important business questions such as:

- Which employees are the top performers?
- What is the average salary and sales?
- Which department performs the best?
- Which employees need improvement?
- Are there any incorrect or inconsistent records?
- What insights can help management make better decisions?

Throughout this notebook, we'll use the NumPy concepts you've already learned to solve these real-world problems step by step.

In [1]:
import numpy as np

In [2]:
import numpy as np

employee_data = np.array([
    [101, 25, 1, 2, 35000, 180000, 4],
    [102, 30, 2, 5, 50000, 220000, 5],
    [103, 28, 1, 4, 42000, 210000, 4],
    [104, 35, 4, 10, 75000, 300000, 5],
    [105, 26, 3, 3, 38000, 150000, 3],
    [106, 40, 4, 15, 90000, 420000, 5],
    [107, 29, 2, 6, 52000, 240000, 4],
    [108, 31, 1, 7, 60000, 260000, 5],
    [109, 27, 3, 4, 41000, 170000, 3],
    [110, 38, 4, 12, 82000, 390000, 5]
])

np.savetxt(
    "employee_data.csv",
    employee_data,
    delimiter=",",
    fmt="%d"
)

print("Dataset saved successfully as 'employee_data.csv'")

Dataset saved successfully as 'employee_data.csv'


In [3]:
data = np.loadtxt("employee_data.csv", delimiter=",", dtype=int)

print(data)

[[   101     25      1      2  35000 180000      4]
 [   102     30      2      5  50000 220000      5]
 [   103     28      1      4  42000 210000      4]
 [   104     35      4     10  75000 300000      5]
 [   105     26      3      3  38000 150000      3]
 [   106     40      4     15  90000 420000      5]
 [   107     29      2      6  52000 240000      4]
 [   108     31      1      7  60000 260000      5]
 [   109     27      3      4  41000 170000      3]
 [   110     38      4     12  82000 390000      5]]


In [4]:
print("Shape:", data.shape)
print("Dimensions:", data.ndim)
print("Data Type:", data.dtype)
print("Total Values:", data.size)

Shape: (10, 7)
Dimensions: 2
Data Type: int64
Total Values: 70


In [5]:
employee_id = data[:, 0]
age = data[:, 1]
department = data[:, 2]
experience = data[:, 3]
salary = data[:, 4]
sales = data[:, 5]
rating = data[:, 6]

In [6]:
print("Employee IDs:\n", employee_id)

print("\nSalaries:\n", salary)

print("\nSales:\n", sales)

Employee IDs:
 [101 102 103 104 105 106 107 108 109 110]

Salaries:
 [35000 50000 42000 75000 38000 90000 52000 60000 41000 82000]

Sales:
 [180000 220000 210000 300000 150000 420000 240000 260000 170000 390000]


In [7]:
print(data[:, [1, 4, 5]])

[[    25  35000 180000]
 [    30  50000 220000]
 [    28  42000 210000]
 [    35  75000 300000]
 [    26  38000 150000]
 [    40  90000 420000]
 [    29  52000 240000]
 [    31  60000 260000]
 [    27  41000 170000]
 [    38  82000 390000]]


In [8]:
high_salary = data[salary > 50000]

print(high_salary)

[[   104     35      4     10  75000 300000      5]
 [   106     40      4     15  90000 420000      5]
 [   107     29      2      6  52000 240000      4]
 [   108     31      1      7  60000 260000      5]
 [   110     38      4     12  82000 390000      5]]


In [9]:
experienced_emp = data[experience > 5]

print(experienced_emp)

[[   104     35      4     10  75000 300000      5]
 [   106     40      4     15  90000 420000      5]
 [   107     29      2      6  52000 240000      4]
 [   108     31      1      7  60000 260000      5]
 [   110     38      4     12  82000 390000      5]]


In [10]:
top_rated = data[rating == 5]

print(top_rated)

[[   102     30      2      5  50000 220000      5]
 [   104     35      4     10  75000 300000      5]
 [   106     40      4     15  90000 420000      5]
 [   108     31      1      7  60000 260000      5]
 [   110     38      4     12  82000 390000      5]]


In [11]:
it_department = data[department == 4]

print(it_department)

[[   104     35      4     10  75000 300000      5]
 [   106     40      4     15  90000 420000      5]
 [   110     38      4     12  82000 390000      5]]


In [12]:
high_performers = data[(salary > 50000) & (rating == 5)]

print(high_performers)

[[   104     35      4     10  75000 300000      5]
 [   106     40      4     15  90000 420000      5]
 [   108     31      1      7  60000 260000      5]
 [   110     38      4     12  82000 390000      5]]


In [18]:
print("Average Salary :", np.mean(salary))
print("Median Salary  :", np.median(salary))
print("Highest Salary :", np.max(salary))
print("Lowest Salary  :", np.min(salary))
print("Salary Std Dev :", np.std(salary))

Average Salary : 56500.0
Median Salary  : 51000.0
Highest Salary : 90000
Lowest Salary  : 35000
Salary Std Dev : 18559.364213248253


In [19]:
print("Average Sales :", np.mean(sales))
print("Median Sales  :", np.median(sales))
print("Highest Sales :", np.max(sales))
print("Lowest Sales  :", np.min(sales))
print("Sales Std Dev :", np.std(sales))

Average Sales : 254000.0
Median Sales  : 230000.0
Highest Sales : 420000
Lowest Sales  : 150000
Sales Std Dev : 86510.11501552867


In [22]:
print("Average Experience :", np.mean(experience))
print("Maximum Experience :", np.max(experience))
print("Minimum Experience :", np.min(experience))

Average Experience : 6.8
Maximum Experience : 15
Minimum Experience : 2


In [25]:
salary_sorted = data[np.argsort(salary)]

print(salary_sorted)

[[   101     25      1      2  35000 180000      4]
 [   105     26      3      3  38000 150000      3]
 [   109     27      3      4  41000 170000      3]
 [   103     28      1      4  42000 210000      4]
 [   102     30      2      5  50000 220000      5]
 [   107     29      2      6  52000 240000      4]
 [   108     31      1      7  60000 260000      5]
 [   104     35      4     10  75000 300000      5]
 [   110     38      4     12  82000 390000      5]
 [   106     40      4     15  90000 420000      5]]


In [26]:
annual_salary = salary * 12

print(annual_salary)

[ 420000  600000  504000  900000  456000 1080000  624000  720000  492000
  984000]


In [35]:
annual_salary = annual_salary.reshape(-1,1 )  
#Here, -1 means:" NumPy, you figure out how many rows are needed."

print(annual_salary)
print(np.shape(annual_salary))

[[ 420000]
 [ 600000]
 [ 504000]
 [ 900000]
 [ 456000]
 [1080000]
 [ 624000]
 [ 720000]
 [ 492000]
 [ 984000]]
(10, 1)


In [37]:
print("Average Age:", np.mean(age))

Average Age: 30.9


In [40]:
highest_salary_employee = data[np.argmax(salary)]

print(highest_salary_employee)

[   106     40      4     15  90000 420000      5]


In [41]:
below_average_salary = data[salary < np.mean(salary)]

print(below_average_salary)

[[   101     25      1      2  35000 180000      4]
 [   102     30      2      5  50000 220000      5]
 [   103     28      1      4  42000 210000      4]
 [   105     26      3      3  38000 150000      3]
 [   107     29      2      6  52000 240000      4]
 [   109     27      3      4  41000 170000      3]]


In [42]:
updated_data = np.hstack((data, annual_salary))

print(updated_data)

[[    101      25       1       2   35000  180000       4  420000]
 [    102      30       2       5   50000  220000       5  600000]
 [    103      28       1       4   42000  210000       4  504000]
 [    104      35       4      10   75000  300000       5  900000]
 [    105      26       3       3   38000  150000       3  456000]
 [    106      40       4      15   90000  420000       5 1080000]
 [    107      29       2       6   52000  240000       4  624000]
 [    108      31       1       7   60000  260000       5  720000]
 [    109      27       3       4   41000  170000       3  492000]
 [    110      38       4      12   82000  390000       5  984000]]


In [44]:
np.savetxt(
    "employee_data_processed.csv",
    updated_data,
    delimiter=",",
    fmt="%d"
)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!
