# 📘 Notebook 17 – Final NumPy Capstone Project

# Student Performance Analysis System (Using Only NumPy)

## 🎯 Project Scenario

You have joined a school as a **Data Analyst**.

The school management has provided the marks of students and wants you to prepare a complete performance report using **only NumPy**.

You are **not allowed to use Pandas**.

Your job is to analyze the data and answer management's questions by applying the NumPy concepts you've learned throughout this roadmap.

---

## 📂 Dataset Description

The dataset contains marks of **20 students** in five subjects.

| Column | Description |
|---------|-------------|
| Student_ID | Unique Student ID |
| Math | Mathematics Marks |
| Science | Science Marks |
| English | English Marks |
| Computer | Computer Marks |
| Social | Social Studies Marks |

Each row represents one student.

---

## 📌 Your Tasks

You need to complete the following company requirements:

1. Load the dataset.
2. Display the dataset.
3. Calculate total marks.
4. Calculate percentage.
5. Find the topper.
6. Find the lowest scorer.
7. Rank all students.
8. Find students scoring above 80%.
9. Find students scoring below 40%.
10. Find students failing in any subject.
11. Find subject-wise highest marks.
12. Find subject-wise lowest marks.
13. Find subject-wise average marks.
14. Find subject-wise median marks.
15. Find subject-wise standard deviation.
16. Find students scoring above the class average.
17. Sort students by percentage.
18. Search for a student using Student ID.
19. Add Total and Percentage columns.
20. Generate the final class performance report.
21. Save the processed dataset.

---

## 🎯 Objective

By the end of this project, you should be able to independently analyze a real dataset using only NumPy.

This project serves as a complete revision of your NumPy roadmap.

In [1]:
#Creation of Dataset
import numpy as np

student_data = np.array([
    [101, 85, 78, 92, 88, 80],
    [102, 67, 74, 70, 72, 68],
    [103, 95, 91, 89, 96, 94],
    [104, 45, 52, 48, 55, 50],
    [105, 76, 81, 79, 84, 77],
    [106, 88, 90, 86, 91, 89],
    [107, 59, 63, 61, 58, 60],
    [108, 99, 98, 97, 100, 99],
    [109, 73, 70, 75, 78, 72],
    [110, 82, 85, 84, 83, 81],
    [111, 39, 42, 38, 45, 40],
    [112, 91, 89, 94, 92, 90],
    [113, 64, 66, 62, 65, 63],
    [114, 55, 58, 60, 57, 59],
    [115, 79, 76, 81, 80, 78],
    [116, 93, 95, 92, 94, 96],
    [117, 48, 50, 46, 49, 47],
    [118, 71, 73, 69, 74, 72],
    [119, 86, 84, 88, 87, 85],
    [120, 62, 60, 64, 61, 63]
])

student_data

array([[101,  85,  78,  92,  88,  80],
       [102,  67,  74,  70,  72,  68],
       [103,  95,  91,  89,  96,  94],
       [104,  45,  52,  48,  55,  50],
       [105,  76,  81,  79,  84,  77],
       [106,  88,  90,  86,  91,  89],
       [107,  59,  63,  61,  58,  60],
       [108,  99,  98,  97, 100,  99],
       [109,  73,  70,  75,  78,  72],
       [110,  82,  85,  84,  83,  81],
       [111,  39,  42,  38,  45,  40],
       [112,  91,  89,  94,  92,  90],
       [113,  64,  66,  62,  65,  63],
       [114,  55,  58,  60,  57,  59],
       [115,  79,  76,  81,  80,  78],
       [116,  93,  95,  92,  94,  96],
       [117,  48,  50,  46,  49,  47],
       [118,  71,  73,  69,  74,  72],
       [119,  86,  84,  88,  87,  85],
       [120,  62,  60,  64,  61,  63]])

In [2]:
#Save the Dataset
np.savetxt(
    "student_marks.csv",
    student_data,
    delimiter=",",
    fmt="%d"
)

print("Dataset saved successfully!")

Dataset saved successfully!


In [3]:
#Load the Dataset
data = np.loadtxt(
    "student_marks.csv",
    delimiter=",",
    dtype=int
)

print(data)

[[101  85  78  92  88  80]
 [102  67  74  70  72  68]
 [103  95  91  89  96  94]
 [104  45  52  48  55  50]
 [105  76  81  79  84  77]
 [106  88  90  86  91  89]
 [107  59  63  61  58  60]
 [108  99  98  97 100  99]
 [109  73  70  75  78  72]
 [110  82  85  84  83  81]
 [111  39  42  38  45  40]
 [112  91  89  94  92  90]
 [113  64  66  62  65  63]
 [114  55  58  60  57  59]
 [115  79  76  81  80  78]
 [116  93  95  92  94  96]
 [117  48  50  46  49  47]
 [118  71  73  69  74  72]
 [119  86  84  88  87  85]
 [120  62  60  64  61  63]]


In [4]:
#Verify the Dataset
print("Shape:", data.shape)
print("Dimensions:", data.ndim)
print("Data Type:", data.dtype)
print("Total Values:", data.size)

Shape: (20, 6)
Dimensions: 2
Data Type: int64
Total Values: 120


Analysis

The dataset contains:

20 students,
6 columns,
2-dimensional array,
120 total values

In [5]:
# Display the First Five Student Records
print(data[:5])

[[101  85  78  92  88  80]
 [102  67  74  70  72  68]
 [103  95  91  89  96  94]
 [104  45  52  48  55  50]
 [105  76  81  79  84  77]]


In [6]:
#Extract Subject Columns
student_id = data[:, 0]
math = data[:, 1]
science = data[:, 2]
english = data[:, 3]
computer = data[:, 4]
social = data[:, 5]
print("Math Marks:")
print(math)

print("\nScience Marks:")
print(science)

Math Marks:
[85 67 95 45 76 88 59 99 73 82 39 91 64 55 79 93 48 71 86 62]

Science Marks:
[78 74 91 52 81 90 63 98 70 85 42 89 66 58 76 95 50 73 84 60]


In [7]:
#Calculate Total 
total_marks = math + science + english + computer + social

print(total_marks)


[423 351 465 250 397 444 301 493 368 415 204 456 320 289 394 470 240 359
 430 310]


In [8]:
# Calculate Percentage
percentage = (total_marks / 500) * 100

print(np.round(percentage, 2))

[84.6 70.2 93.  50.  79.4 88.8 60.2 98.6 73.6 83.  40.8 91.2 64.  57.8
 78.8 94.  48.  71.8 86.  62. ]


In [9]:
# Add Derived Columns - Total Marks   - Percentage
total_marks = total_marks.reshape(-1, 1)
percentage = percentage.reshape(-1, 1)
updated_data = np.hstack((data, total_marks, percentage))
print(updated_data)

[[101.   85.   78.   92.   88.   80.  423.   84.6]
 [102.   67.   74.   70.   72.   68.  351.   70.2]
 [103.   95.   91.   89.   96.   94.  465.   93. ]
 [104.   45.   52.   48.   55.   50.  250.   50. ]
 [105.   76.   81.   79.   84.   77.  397.   79.4]
 [106.   88.   90.   86.   91.   89.  444.   88.8]
 [107.   59.   63.   61.   58.   60.  301.   60.2]
 [108.   99.   98.   97.  100.   99.  493.   98.6]
 [109.   73.   70.   75.   78.   72.  368.   73.6]
 [110.   82.   85.   84.   83.   81.  415.   83. ]
 [111.   39.   42.   38.   45.   40.  204.   40.8]
 [112.   91.   89.   94.   92.   90.  456.   91.2]
 [113.   64.   66.   62.   65.   63.  320.   64. ]
 [114.   55.   58.   60.   57.   59.  289.   57.8]
 [115.   79.   76.   81.   80.   78.  394.   78.8]
 [116.   93.   95.   92.   94.   96.  470.   94. ]
 [117.   48.   50.   46.   49.   47.  240.   48. ]
 [118.   71.   73.   69.   74.   72.  359.   71.8]
 [119.   86.   84.   88.   87.   85.  430.   86. ]
 [120.   62.   60.   64.   61. 

In [10]:
#Find the Topper
topper = updated_data[np.argmax(updated_data[:, 7])]
print("Topper Details:")
print(topper)



Topper Details:
[108.   99.   98.   97.  100.   99.  493.   98.6]


In [11]:
#Find the Lowest Scorer
lowest_scorer = updated_data[np.argmin(updated_data[:, 7])]
print("Lowest Scorer Details:")
print(lowest_scorer)


Lowest Scorer Details:
[111.   39.   42.   38.   45.   40.  204.   40.8]


In [12]:
#Generate the Merit List
merit_list = updated_data[np.argsort(updated_data[:, 7])[::-1]]
print(merit_list)

[[108.   99.   98.   97.  100.   99.  493.   98.6]
 [116.   93.   95.   92.   94.   96.  470.   94. ]
 [103.   95.   91.   89.   96.   94.  465.   93. ]
 [112.   91.   89.   94.   92.   90.  456.   91.2]
 [106.   88.   90.   86.   91.   89.  444.   88.8]
 [119.   86.   84.   88.   87.   85.  430.   86. ]
 [101.   85.   78.   92.   88.   80.  423.   84.6]
 [110.   82.   85.   84.   83.   81.  415.   83. ]
 [105.   76.   81.   79.   84.   77.  397.   79.4]
 [115.   79.   76.   81.   80.   78.  394.   78.8]
 [109.   73.   70.   75.   78.   72.  368.   73.6]
 [118.   71.   73.   69.   74.   72.  359.   71.8]
 [102.   67.   74.   70.   72.   68.  351.   70.2]
 [113.   64.   66.   62.   65.   63.  320.   64. ]
 [120.   62.   60.   64.   61.   63.  310.   62. ]
 [107.   59.   63.   61.   58.   60.  301.   60.2]
 [114.   55.   58.   60.   57.   59.  289.   57.8]
 [104.   45.   52.   48.   55.   50.  250.   50. ]
 [117.   48.   50.   46.   49.   47.  240.   48. ]
 [111.   39.   42.   38.   45. 

In [13]:
#Find Students Scoring Above 80%
high_performers = updated_data[updated_data[:, 7] > 80]
print(high_performers)

[[101.   85.   78.   92.   88.   80.  423.   84.6]
 [103.   95.   91.   89.   96.   94.  465.   93. ]
 [106.   88.   90.   86.   91.   89.  444.   88.8]
 [108.   99.   98.   97.  100.   99.  493.   98.6]
 [110.   82.   85.   84.   83.   81.  415.   83. ]
 [112.   91.   89.   94.   92.   90.  456.   91.2]
 [116.   93.   95.   92.   94.   96.  470.   94. ]
 [119.   86.   84.   88.   87.   85.  430.   86. ]]


In [14]:
#Find Students Scoring Below 40%
below_40 = updated_data[updated_data[:, 7] < 40]
print(below_40)

[]


In [15]:
# Find Students Failing in Any Subject
failing_students = updated_data[
    (updated_data[:, 1] < 40) |
    (updated_data[:, 2] < 40) |
    (updated_data[:, 3] < 40) |
    (updated_data[:, 4] < 40) |
    (updated_data[:, 5] < 40)
]

print(failing_students)

[[111.   39.   42.   38.   45.   40.  204.   40.8]]


In [16]:
#Subject-wise Highest Marks
print("Highest Marks")
print("Math     :", np.max(math))
print("Science  :", np.max(science))
print("English  :", np.max(english))
print("Computer :", np.max(computer))
print("Social   :", np.max(social))

Highest Marks
Math     : 99
Science  : 98
English  : 97
Computer : 100
Social   : 99


In [17]:
#Subject-wise Lowest Marks
print("Lowest Marks")
print("Math     :", np.min(math))
print("Science  :", np.min(science))
print("English  :", np.min(english))
print("Computer :", np.min(computer))
print("Social   :", np.min(social))

Lowest Marks
Math     : 39
Science  : 42
English  : 38
Computer : 45
Social   : 40


In [18]:
#Subject-wise Statistics
subjects = {
    "Math": math,
    "Science": science,
    "English": english,
    "Computer": computer,
    "Social": social
}

for subject, marks in subjects.items():
    print(f"\n{subject}")
    print("Average :", np.mean(marks))
    print("Median  :", np.median(marks))
    print("Std Dev :", round(np.std(marks), 2))


Math
Average : 72.85
Median  : 74.5
Std Dev : 17.14

Science
Average : 73.75
Median  : 75.0
Std Dev : 15.51

English
Average : 73.75
Median  : 77.0
Std Dev : 16.91

Computer
Average : 75.45
Median  : 79.0
Std Dev : 16.36

Social
Average : 73.15
Median  : 74.5
Std Dev : 16.39


In [19]:
#Find Students Scoring Above the Class Average
class_average = np.mean(updated_data[:, 7])
print("Class Average Percentage:", round(class_average, 2))
above_average = updated_data[updated_data[:,7] > class_average]
print(above_average)

Class Average Percentage: 73.79
[[101.   85.   78.   92.   88.   80.  423.   84.6]
 [103.   95.   91.   89.   96.   94.  465.   93. ]
 [105.   76.   81.   79.   84.   77.  397.   79.4]
 [106.   88.   90.   86.   91.   89.  444.   88.8]
 [108.   99.   98.   97.  100.   99.  493.   98.6]
 [110.   82.   85.   84.   83.   81.  415.   83. ]
 [112.   91.   89.   94.   92.   90.  456.   91.2]
 [115.   79.   76.   81.   80.   78.  394.   78.8]
 [116.   93.   95.   92.   94.   96.  470.   94. ]
 [119.   86.   84.   88.   87.   85.  430.   86. ]]


In [20]:
 #Search for a Student
student = updated_data[updated_data[:, 0] == 116]
print(student)

[[116.  93.  95.  92.  94.  96. 470.  94.]]


In [21]:
#Final Merit List
print(merit_list)

[[108.   99.   98.   97.  100.   99.  493.   98.6]
 [116.   93.   95.   92.   94.   96.  470.   94. ]
 [103.   95.   91.   89.   96.   94.  465.   93. ]
 [112.   91.   89.   94.   92.   90.  456.   91.2]
 [106.   88.   90.   86.   91.   89.  444.   88.8]
 [119.   86.   84.   88.   87.   85.  430.   86. ]
 [101.   85.   78.   92.   88.   80.  423.   84.6]
 [110.   82.   85.   84.   83.   81.  415.   83. ]
 [105.   76.   81.   79.   84.   77.  397.   79.4]
 [115.   79.   76.   81.   80.   78.  394.   78.8]
 [109.   73.   70.   75.   78.   72.  368.   73.6]
 [118.   71.   73.   69.   74.   72.  359.   71.8]
 [102.   67.   74.   70.   72.   68.  351.   70.2]
 [113.   64.   66.   62.   65.   63.  320.   64. ]
 [120.   62.   60.   64.   61.   63.  310.   62. ]
 [107.   59.   63.   61.   58.   60.  301.   60.2]
 [114.   55.   58.   60.   57.   59.  289.   57.8]
 [104.   45.   52.   48.   55.   50.  250.   50. ]
 [117.   48.   50.   46.   49.   47.  240.   48. ]
 [111.   39.   42.   38.   45. 

In [22]:
 #Save the Processed Dataset
np.savetxt(
    "student_marks_processed.csv",
    updated_data,
    delimiter=",",
    fmt="%.2f"
)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!


In [23]:

print("        CLASS PERFORMANCE REPORT")

print(f"Total Students            : {len(student_id)}")
print(f"Class Average Percentage  : {np.mean(percentage):.2f}%")
print(f"Highest Percentage        : {np.max(percentage):.2f}%")
print(f"Lowest Percentage         : {np.min(percentage):.2f}%")
print(f"\nStudents Above 80%        : {len(high_performers)}")
print(f"Students Below 40%        : {len(below_40)}")
print(f"Students Failed           : {len(failing_students)}")
print("\nTopper Student ID         :", int(topper[0]))
print(f"Topper Percentage         : {topper[7]:.2f}%")



        CLASS PERFORMANCE REPORT
Total Students            : 20
Class Average Percentage  : 73.79%
Highest Percentage        : 98.60%
Lowest Percentage         : 40.80%

Students Above 80%        : 8
Students Below 40%        : 0
Students Failed           : 1

Topper Student ID         : 108
Topper Percentage         : 98.60%
